### ISSUE TITLE
Schedule for the week 

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/LWC#1]
Hey @mandytaylorlwc,

__Build days:__
Thursday 14th Dec
Friday 15th Dec
Monday 18th Dec 

__Presentation Day__
Tuesday 19th Dec

Is there a time on Tuesday that you would like to have a call to go through the product? We can do this via a hangouts call ☎️

**Comment by mandytaylorlwc** [comment]
Hi

Good luck with this am trying to answer all the questions this morning and Tuesday  can you call at 2pm as in a meeting in the morning and need to get back to the centre.

thanks

**Comment by Jen-Harris** [comment]
Hey @mandytaylorlwc, 2pm on Tuesday works well for us 👍
