### ISSUE TITLE
Designs

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/LWC#10]
Hey @mandytaylorlwc,
@maxgerber and I have been working on the designs today. Please let us know what you think...

1. User lands on page and is given option 'need advice' or 'know what you need' and then will be either routed to quotes from women or a list of LWC services. We chose an image of a couple of women holding hands in the background - let us know if you would prefer something else. 

![image](https://user-images.githubusercontent.com/26116988/33999335-1ef3b112-e0e2-11e7-8d66-fd0ca94fce79.png)
  
2. If the user choose to have advice they would get a list of quotes from users where they have the option to find out more if they want 
  
![image](https://user-images.githubusercontent.com/26116988/33999401-4bfb963e-e0e2-11e7-8892-49f93e609796.png)
  
3. If the user chooses to see more then they will get a more detailed description of what happened to the woman including what services they used. 
  
![image](https://user-images.githubusercontent.com/26116988/33999516-9d2816d6-e0e2-11e7-8a59-6f064f76b9db.png)

 4. If they want to see the full list of services it could be in the form of a list with an option drop down to show the user more information (if this is something you like we would need the additional details / we can just use 'lorem ipsum' text)
 
![image](https://user-images.githubusercontent.com/26116988/33999599-c8cca34c-e0e2-11e7-96c7-0141e31010ca.png)
  
5. If the user wants to talk to LWC they are given three option - come to a centre, call or be contacted 

  
![image](https://user-images.githubusercontent.com/26116988/33999627-dcd1b242-e0e2-11e7-85e7-6833bd9e7850.png)

  
6. If they choose to be contacted then there is the short form to fill in 
  
![image](https://user-images.githubusercontent.com/26116988/33999644-ef68cca6-e0e2-11e7-9da4-7b6b1add79f9.png)

7. Then if the user fills in the form they go to a thank you page and given a time scale for when LWC will be in touch 

![image](https://user-images.githubusercontent.com/26116988/33999705-19136a98-e0e3-11e7-9dad-ad01993c5610.png)

Please let us know what you think - any comments, amends etc. We're happy to jump on a call this afternoon if you think that would be helpful as well. 

Also, if these images are a bit small you can see the designs [here](https://www.figma.com/file/UkADRtfuYVzlYDOaPcPehzhb/Lancashire-Women-s-Centre) as well

Jen

**Comment by mandytaylorlwc** [comment]
Hi

Thanks this looks amazing, am just going to let Liz have a quick nosey when she is in at lunch, and will ask someone to start writing some bloggs on services to let you have, general consensus is good not sure on the word advice on first page thinking maybe support?  but will come back to you after lunch today.

thanks

**Comment by Jen-Harris** [comment]
Great, thanks @mandytaylorlwc, 
Let us know if Liz has any additional feedback. and in the meantime we'll reword advice to support 
Jen

**Comment by mandytaylorlwc** [comment]
Hello liz here, commenting on mandy's page :)

Looks great - two observations:
 - Stock photos - this might be too much detail but think getting the right image is crucial and links to the stuff around women feeling confident to step in as we are run by and run for women 'like me' - could we get some local photos, or is this better done later?
 - List of services - i think there are too many and they don't all sound obvious to the person on the street - e.g. we know what breaking the cycle does but do other people?  I think we reduce into a small number of general headings like employment support, therapy, money advice etc - do we need to think what these should be?  I think we often provide to much minute detail that probably only makes sense to LWC staff!

**Comment by Jen-Harris** [comment]
Hey @mandytaylorlwc / Liz! 
Thanks for the comments, both really valid points! 

* In terms of images, do you have any you would like us to use? We're happy to put in any images you prefer. 
* We can absolutely reduce the services list. Which services would you like to be included? We can then go into a bit more detail on the drop down as well if you like.

**Comment by Jen-Harris** [comment]
Hey @mandytaylorlwc, 
Just wondering about the above? 
The main thing that would be great to get today is the final list of services and what additional info you would like in each of the drop downs (if any)! 
Thanks!

**Comment by mandytaylorlwc** [comment]
![slv_8750](https://user-images.githubusercontent.com/34453845/34104097-13e02b0e-e3e7-11e7-9397-d97c718cfba0.jpg)
![slv_8596](https://user-images.githubusercontent.com/34453845/34104098-13f67062-e3e7-11e7-8870-843a88565ea9.jpg)
![slv_8605](https://user-images.githubusercontent.com/34453845/34104100-140e8580-e3e7-11e7-8f3c-e2ad008c5125.jpg)
![slv_8329](https://user-images.githubusercontent.com/34453845/34104101-1423a118-e3e7-11e7-8d51-042f15e36d47.jpg)
![clients in reception](https://user-images.githubusercontent.com/34453845/34104102-1438582e-e3e7-11e7-81b9-1956744b9847.jpg)
![bodyfit 6](https://user-images.githubusercontent.com/34453845/34104103-144d4e64-e3e7-11e7-89e8-cc10b892dc8f.jpg)
![slv_8564](https://user-images.githubusercontent.com/34453845/34104117-2326f926-e3e7-11e7-8c8d-576372244147.jpg)

**Comment by mandytaylorlwc** [comment]
**Talking therapies** - Our Talking Therapies can help you if you are experiencing: 

low mood
anxiety
worry
panic
bereavement 
relationship difficulties
poor sleep
low self-esteem

Our services are open to anybody over the age of 16 who may be experiencing any of these problems and want to feel better.   We also have a number of therapists with specialised skills that can support you to improve your thoughts and feelings and improve your emotional wellbeing.

These include:

Living Well - if you have a long term physical health problem or a physical symptom that cannot be diagnosed.

Perinatal - if you or your partner is pregnant or have given birth within the last 12 months.

Victims of crime - specialist support for adults and children who have been a victim of crime such as: hate crime, domestic or sexual abuse and we can also support with pre-trial therapy. 

NICU - specialist support if you have had experience of NICU (neonatal intensive care unit) at any time. We understand that this can be a high time of distress for families and we often parents and extended family accessing our mental health services.

Talking Therapies enable you to improve your mood, build confidence and self esteem and feel better about your emotional and physical health and have better relationships with others. 

**Personal Development and Training** - Our training provision provides both  entry point into support and progression route within our services, with our programmes designed to deliver a responsive educational programme of wellbeing and mental health recovery focussed workshops and courses.   Our MindFit programme of therapeutic courses include the Programme, centred around our recommended route a carefully designed progression package which leads individuals to improved wellbeing. 

MindFit has been developed to provide a voyage of self discovery, with learners progressing carefully through a series of 5 week long courses.  

Courses in the programme include:

The Planner - the first steps to feeling  happier, welcome and at ease in a small group. 

The Journey - leads to feeling stronger, more confident and assertive. 

The Prize -  which adds the final touches and polishes new skills to achieve lasting positive changes.

**Employment Support** - Our Employment Support Team provide an individually tailored service for any person looking to gain employment, go into education, volunteering or job searching.Our experienced staff will work with you on a one to one basis to develop your own personal action plan and support you to achieve your goals.

Our package of support includes:

* Workshops and Training Courses to help you build your CV, develop interview skills, build your confidence and  identify your strengths and skills.
* Volunteer led work clubs to support with job searching and CV building.
* Digital inclusion and IT support on a 1 to 1 or group basis.
* Support to find the right training course and qualifications.
* Volunteer placement opportunities to enhance your portfolio and develop your work skills.
* Money advice  and support.
* Support find the right childcare provision 
* Access to therapeutic services, including one to one support and group activity to boost your confidence and self-esteem. 
* legal Clinics - We work with a number of local solicitors who provide free legal clinics at our centres.

**Money, Debt and Benefit Advice** - Lancashire Women's Centres offer a Financial Conduct Authority (FCA) regulated debt counselling  and money advice appointments offering a range of services. 

Such as: 

* Benefit advice including rent arrears,
* Benefit applications
* Mandatory reconsiderations and appeals
* Debt issues and options, 
* Back to work calculations
* Budgeting advice.
* legal Clinics - We work with a number of local solicitors who provide free legal clinics at our centres.
Sessions are delivered out of each of our centres and work in partnership with Shelter within Blackburn Library. 

We offer 1-to-1 sessions by experienced staff offering support and impartial advice to those in need.

**Volunteering and Mentoring** - Use your Skills, Life Experiences and Spare Time to Support Others, Volunteers are at the heart of our centres. If you want to get involved, meet new people, learn new skills or rediscover old ones then please get in touch with your local centre.   We have lots of projects and work streams were we are dependent on Volunteers and Mentor and we also need general volunteers and mentors as there are times in all our lives when we could really benefit from the help of another person. We might just want someone to discuss options with, someone to talk through ideas for the future or support with forms and appointments or advice on the internal services we can offer.  Mentoring offers you the opportunity to develop a relationship that is based on trust, confidentiality and mutual involvement to set goals and decide achievements.  Your sessions will involve setting personal goals, guidance and action planning to help a successful outcome.  

** Women within the Criminal Justice System** - We continue to build upon the recommendations of Baroness Corston’s 2007 report into women in the criminal justice system and have developed a package of services which provide a gendered considered response to the issues of female offending behaviour.   Using this approach, we support a number of localised multi agency programmes where we are able to use our expertise in the provision of gender specific interventions to improve outcomes for women.  We now offer a package of services which work with women at all points in the criminal justice system, as well as women at risk of offending, placing staff within police custody and prison settings to support engagement as well as further extending our community provision.

**Comment by mandytaylorlwc** [comment]
hi we have reduced the number of services to include main headers as above (women within the criminal justice system is also a header)

**Comment by mandytaylorlwc** [comment]
sorry can we change talking therapies to therapeutic services/emotional wellbeing

and Women within the Criminal Justice System to Women in Crisis/Complex needs/in the Criminal Justice System

can we also add

** Meeting Others** - Our Peer Support Groups  i.e. BETTER TOGETHER - for continued Mental Health & Wellbeing Come along to this informal, friendly peer support group for a brew & chat

**Comment by Jen-Harris** [comment]
Great, thanks @mandytaylorlwc. We'll incorporate these changes this afternoon. 

With the images, where did you imagine these going? I thought you were referring to the images we have included of the individual women in the quotes section?
![image](https://user-images.githubusercontent.com/26116988/34109781-91d1f384-e3fc-11e7-9995-51f879dd8638.png)

**Comment by mandytaylorlwc** [comment]
These can replace the images you used, as they show women in service.

thanks

Mandy Taylor BA hons, PGCE, MCIH, MIMA (Cert)
Project Manager (Employment, Advice and Guidance)
Lancashire Women’s Centres

Secure email: Mandy.taylor@womenscentre.cjsm.net<mailto:Mandy.taylor@womenscentre.cjsm.net>
#EveryWomanCounts    #WellbeingMatters

Website: www.womenscentre.org<http://www.womenscentre.org/>
Follow us on Twitter @WomensCentred  or on Facebook at Lancashire Women’s Centres

   [cid:image001.png@01D2F4D2.88F43160]

Accrington Centre:          21-23 Blackburn Road, Accrington, BB5 1HF                         Tel. 01254 871771
Blackburn Centre:           25 Wellington Street (St.John’s), Blackburn, BB1 8AF      Tel. 01254 583032
Blackpool Centre:            162 Church Street, Blackpool, FY1 3PS                                    Tel. 01253 290007
Burnley Centre:                4 Nicholas Street, Burnley, BB11 2EU                                      Tel. 01282 429672
Preston Centre:                31 Fishergate Hill, Preston, PR1 8DN                                       Tel. 01772 259211

Freephone 0808 280 3160

This message and any files transmitted with it are confidential and intended solely for the individual(s) addressed. If you have received this e-mail in error then please note that disclosing, copying or distributing from your system is strictly prohibited. Any views or opinions presented are solely those of the author and do not necessarily represent those of Lancashire Women’s Centres. The organisation accepts no liability for any damage caused by any virus transmitted with this e-mail, so although it has been virus checked before transmission, the recipient should also check for the presence of viruses.  The confidentiality of this email and any subsequent reply cannot be guaranteed
