### ISSUE TITLE
Follow up fixes from presentation

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/LWC#113]
success criteria: 
- [x] Rename "personal development" to "Courses and Wellbeing"
- [x] Rename "Emotional Wellbeing" to "Therapy" 
- [x] Pull through the new names into the form & airtable as well 
- [x] Services page heading the be correct 
- [x] GDPR statements and error messages to be adjusted. @AmberMCowell and @mandytaylorlwc let us know when you have re-worded this!
- [x] Guide for airtable 
- [x] Email to be an optional choice for users
- [x] typo in URL - URL is now [https://womenscentre.herokuapp.com](https://womenscentre.herokuapp.com)

**Comment by m4v15** [comment]
![airtable2 - testimonials-cards](https://user-images.githubusercontent.com/23310908/35438549-e1534a4c-028e-11e8-8198-e5a016b06b34.gif)
![airtable2 - testimonials-views](https://user-images.githubusercontent.com/23310908/35438550-e16d181e-028e-11e8-9bc0-948b9f9b20a5.gif)
![airtable2 - testimonials](https://user-images.githubusercontent.com/23310908/35438551-e184a3d0-028e-11e8-9888-d1a83ce0fcb2.gif)
![airtable2 - print](https://user-images.githubusercontent.com/23310908/35438552-e19bfa94-028e-11e8-9278-f55ac52989a6.gif)
![airtable2 - export](https://user-images.githubusercontent.com/23310908/35438553-e1b55610-028e-11e8-9380-43a2b17104e8.gif)
![airtable2 - views-kanban](https://user-images.githubusercontent.com/23310908/35438554-e1cecb18-028e-11e8-8375-636cd40d9b25.gif)
![airtable2 - views](https://user-images.githubusercontent.com/23310908/35438555-e1e7c820-028e-11e8-86da-67f118c866bb.gif)
![airtable2 - sort](https://user-images.githubusercontent.com/23310908/35438556-e20009d0-028e-11e8-88d3-acb5a4c8042c.gif)
![airtable2 - group](https://user-images.githubusercontent.com/23310908/35438557-e219fb88-028e-11e8-942c-667cc0ccbb35.gif)
![airtable1](https://user-images.githubusercontent.com/23310908/35438558-e2371dd0-028e-11e8-9c96-97d02d1e0f6a.gif)

**Comment by mandytaylorlwc** [comment]
Hi

We need to put a statement to say,

" if you do not agree to our privacy policy your information cannot be submitted, please contact your local centre"

the rest of it is ok we just need to make the email part optional.

Thanks
