### ISSUE TITLE
List of services

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/LWC#2]
Hey @mandytaylorlwc, 
would you be able to provide us with the list of services you would like us to include in the app? 
Thanks!

**Comment by mandytaylorlwc** [comment]
* Talking Therapies & Emotional Wellbeing specialising in:- 1 to 1 therapeutic support,  Perinatal Support, Victims of Crime, Support for people with experience of babies in NICU, Living well - support for those with Long term health conditions.

* Personal Development and Training

* Employment Support - assorted support with key support workers on a 1 to 1 basis.

* Money, Debt and Benefit Advice - 1 to 1 appointments dealing with all money issues from rent arrears, debt to benefit problems

* STEP ( Succeed, Thrive, Empower, Pennine) - working with people with complex needs who access A & E frequently

* Peer Support Groups

* Mindfit Groups - Training to support emotional wellbeing

* Bodyfit - Training to support physical wellbeing

* Digital Support

* Legal Clinics

* Training for your workplace

* Volunteering

* Mentoring

* Family work (only in Blackburn with Darwen) 

* Breaking the cycle - supportive work for people who have suffered in a  DV relationship (only in Blackburn with Darwen)

**Comment by Jen-Harris** [comment]
This is great, thanks @mandytaylorlwc
