### ISSUE TITLE
Buzzwords!

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/LWC#5]
You mentioned using some key buzzwords 🐝 
What exactly are these? And where should they be included? 
Thanks!

**Comment by mandytaylorlwc** [comment]
A page "need help but not sure what?"  where is says is this you or worried about, need help with? incorporates buzz words and service user story/pics
"anxiety, worry, stress, panic attacks, need to talk, separation, bereavement, debt, benefits, sanctions, low income, employment, need a job, volunteering, computer help, digital support, therapy, physical health conditions, mental health worries, crime, COPD, Asthma , cancer, work clubs, job search, CV, BBO, finding a job, disclosure, mentoring, peer support, phobias, victim of crime, going to court.

this is a start may want amending deleting

**Comment by Jen-Harris** [comment]
Thanks @mandytaylorlwc !
