### ISSUE TITLE
Updated mobile designs for feedback

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/LWC#50]
Hey @mandytaylorlwc !
I've worked on tweaking the mobile designs this morning to help add clarity to the flow - I think it's looking good. 
Please let me know your thoughts on the below and whether you would like any changes. 

__1. Home Screen__
I've turned the 2 buttons into 3 with clearer titles of "See real stories", "See our services" and "contact us". 
I think this will help people who don't want to see the testimonials go straight to the services page and allow people to contact directly. 

![image](https://user-images.githubusercontent.com/26116988/34948885-51e5947c-fa06-11e7-89d5-8c1bef361b54.png)

__2. Navbar__
There were a lot of comments about the nav bar not working (as there wasn't time to include this in the design sprint!). We would like to incorporate this during the build, following the same design of your main LWC website. 
At the moment we've kept the options to go to only within the service searching app. Perhaps we should include a link to go back to the main LWC home page as well? 

![image](https://user-images.githubusercontent.com/26116988/34948967-93c5211e-fa06-11e7-845b-b0d3a22be3b5.png)

__3. links to content__
At the end of the longer quotes we've added a button to help users navigate to the specific service so they don't have to manually look through the page 

![image](https://user-images.githubusercontent.com/26116988/34949023-c25cde36-fa06-11e7-9b18-01e2676fe596.png)

__4. Contact us on services page__
Similarly on the services page we would like to include a 'contact us' button in each of the drop downs so the user can more easily navigate 

![image](https://user-images.githubusercontent.com/26116988/34949061-e0900b9e-fa06-11e7-9b28-c8e4d50a27be.png)

__5. Contact page button__
There was some user feedback that the contact page buttons were a bit small. So we propose that we put the information in boxes and make the whole thing clickable? 

![image](https://user-images.githubusercontent.com/26116988/34949091-01264256-fa07-11e7-98e9-bcfb4940b7dd.png)

__6. Form information__
At the bottom of the form we've added some extra detail to indicate the service the user is interested in and any further information. Please let us know if these are the kinds of questions you imagined  

![image](https://user-images.githubusercontent.com/26116988/34949126-1d7287da-fa07-11e7-889f-582e1c465d4f.png)

__7. Error page__
If an error occurs for the user when sending the data to the spreadsheet it would be nice to have an error page in the flow!

![image](https://user-images.githubusercontent.com/26116988/34949174-42a63b64-fa07-11e7-9eb4-856f9957ca64.png)

We know you're super busy today so don't worry about replying tonight. If you can get back to us tomorrow that would be perfect! You can check out the full flow [here as well](https://www.figma.com/file/UkADRtfuYVzlYDOaPcPehzhb/Lancashire-Women's-Centre)
Will send ipad designs before the end of the day as well. 

Jen

**Comment by mandytaylorlwc** [comment]
this all looks good, is it possible we can have a link to this as a prototype or do we need to continue with the one we have?   not 100% on the wording so need to show a few people - emotional wellbeing - therapy Personal development - Courses.  we need to have a think on the real stories as well hope that ok

**Comment by Jen-Harris** [comment]
Hey @mandytaylorlwc,
At the moment these are just static designs for proposed changes to the app so unfortunately not clickable. 
It would be great to know if overall you're happy so we can make progress with building this? Copy changes are fine to change after the rest is in place. 
Jen
