### ISSUE TITLE
QA workflow

### ISSUE THREAD

**Issue by m4v15** [InFact-coop/LWC#64]
Hey @ivanmauricio 

We mentioned it yesterday I guess but didn't actually decide on a workflow. It looks like it's mostly gonna be me dev-ing and @Jen-Harris designing + doing some front end dev-ing, not sure how you want us to work on it. I would kinda like a bit of QA, and as we're not in a rush, can we just assign you to PR's to review/merge? Would you have enough time this week and next to review them relatively quickly?

**Comment by Jen-Harris** [comment]
...
