### ISSUE TITLE
Photographs 

### ISSUE THREAD

**Issue by AmberMCowell** [InFact-coop/LWC#89]
![image1](https://user-images.githubusercontent.com/35597200/35150924-3ab21332-fd14-11e7-9398-a107283dec60.jpeg)
![image2](https://user-images.githubusercontent.com/35597200/35150926-3acda160-fd14-11e7-9922-d798b421a573.jpeg)
![image3](https://user-images.githubusercontent.com/35597200/35150928-3ae95108-fd14-11e7-83fa-44701e42cb20.jpeg)

Hello, I've taken 3 photographs that we can use and have permission for them to be used on our app.

**Comment by AmberMCowell** [comment]
will take more as soon as I can :)

**Comment by Jen-Harris** [comment]
Brilliant thank you @AmberMCowell ! 
I was thinking we should also say on the quotes page something like 'these stories are real but we've changed the names and images to keep identities confidential' ?

**Comment by Jen-Harris** [comment]
Hey @AmberMCowell, 

Do you have another 3 photos we can use? If not we can keep the current photos in place.

Jen

**Comment by AmberMCowell** [comment]
We have another 3… I’m just waiting for the signed consent to come back to me… is it okay if I send them to you by half 12?

Kind regards,
Amber Cowell
Programme Administrator
Lancashire Women’s Centres

#EveryWomanCounts    #WellbeingMatters

Website: www.womenscentre.org<http://www.womenscentre.org/>
Follow us on Twitter @WomensCentred  <https://twitter.com/WomensCentred> or on Facebook at Lancashire Women’s Centres<https://www.facebook.com/LancashireWomensCentres>

Accrington Centre:          21-23 Blackburn Road, Accrington, BB5 1HF                        <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.752598,-2.3651487,17z/data=!3m1!4b1!4m5!3m4!1s0x487b98e124d6ab5d:0x7bc5d3d6667714f2!8m2!3d53.752598!4d-2.36296>  Tel. 01254 871771
Blackburn Centre:           25 Wellington Street (St.John’s), Blackburn, BB1 8AF     <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.7526822,-2.4329996,12z/data=!4m8!1m2!2m1!1sBlackburn+lancashire+women's+centres!3m4!1s0x487b9fd28f0b563f:0xf10ab08a862d4f5e!8m2!3d53.752363!4d-2.487995>  Tel. 01254 583032
Blackpool Centre:            162 Church Street, Blackpool, FY1 3PS                                   <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.8186884,-3.0498327,18z/data=!4m8!1m2!2m1!1sBlackpool+lancashire+women's+centres!3m4!1s0x487b4479d15b2e1f:0x4f89954f84f43b26!8m2!3d53.8181!4d-3.047073>  Tel. 01253 290007
Burnley Centre:                4 Nicholas Street, Burnley, BB11 2EU                                     <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.7877591,-2.2450177,17z/data=!3m1!4b1!4m5!3m4!1s0x487b9726a2ce562d:0x4d611847e6a9f5e4!8m2!3d53.787756!4d-2.242829>  Tel. 01282 429672
Preston Centre:                31 Fishergate Hill, Preston, PR1 8DN                                      <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.7547675,-2.7157778,17z/data=!3m1!4b1!4m5!3m4!1s0x487b727f53e253d3:0xb88145deea32e318!8m2!3d53.7547643!4d-2.7135891>  Tel. 01772 259211

Freephone: 0808 280 3160

This message and any files transmitted with it are confidential and intended solely for the individual(s) addressed.  If you have received this e-mail in error then please note that disclosing, copying or distributing from your system is strictly prohibited.  Any views or opinions presented are solely those of the author and do not necessarily represent those of Lancashire Women's Centres. The organisation accepts no liability for any damage caused by any virus transmitted with this e-mail, so although it has been virus checked before transmission, the recipient should also check for the presence of viruses.  The confidentiality of this email and any subsequent reply cannot be guaranteed

**Comment by Jen-Harris** [comment]
Sounds great, thanks!

**Comment by AmberMCowell** [comment]
Hello,

Please find attached 2 more pictures for the app ☺

Amber Cowell
Programme Administrator
Lancashire Women’s Centres

#EveryWomanCounts    #WellbeingMatters

Website: www.womenscentre.org<http://www.womenscentre.org/>
Follow us on Twitter @WomensCentred  <https://twitter.com/WomensCentred> or on Facebook at Lancashire Women’s Centres<https://www.facebook.com/LancashireWomensCentres>

Accrington Centre:          21-23 Blackburn Road, Accrington, BB5 1HF                        <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.752598,-2.3651487,17z/data=!3m1!4b1!4m5!3m4!1s0x487b98e124d6ab5d:0x7bc5d3d6667714f2!8m2!3d53.752598!4d-2.36296>  Tel. 01254 871771
Blackburn Centre:           25 Wellington Street (St.John’s), Blackburn, BB1 8AF     <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.7526822,-2.4329996,12z/data=!4m8!1m2!2m1!1sBlackburn+lancashire+women's+centres!3m4!1s0x487b9fd28f0b563f:0xf10ab08a862d4f5e!8m2!3d53.752363!4d-2.487995>  Tel. 01254 583032
Blackpool Centre:            162 Church Street, Blackpool, FY1 3PS                                   <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.8186884,-3.0498327,18z/data=!4m8!1m2!2m1!1sBlackpool+lancashire+women's+centres!3m4!1s0x487b4479d15b2e1f:0x4f89954f84f43b26!8m2!3d53.8181!4d-3.047073>  Tel. 01253 290007
Burnley Centre:                4 Nicholas Street, Burnley, BB11 2EU                                     <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.7877591,-2.2450177,17z/data=!3m1!4b1!4m5!3m4!1s0x487b9726a2ce562d:0x4d611847e6a9f5e4!8m2!3d53.787756!4d-2.242829>  Tel. 01282 429672
Preston Centre:                31 Fishergate Hill, Preston, PR1 8DN                                      <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.7547675,-2.7157778,17z/data=!3m1!4b1!4m5!3m4!1s0x487b727f53e253d3:0xb88145deea32e318!8m2!3d53.7547643!4d-2.7135891>  Tel. 01772 259211

Freephone: 0808 280 3160

This message and any files transmitted with it are confidential and intended solely for the individual(s) addressed.  If you have received this e-mail in error then please note that disclosing, copying or distributing from your system is strictly prohibited.  Any views or opinions presented are solely those of the author and do not necessarily represent those of Lancashire Women's Centres. The organisation accepts no liability for any damage caused by any virus transmitted with this e-mail, so although it has been virus checked before transmission, the recipient should also check for the presence of viruses.  The confidentiality of this email and any subsequent reply cannot be guaranteed

**Comment by AmberMCowell** [comment]
And another! Thanks ☺ Speak tomorrow

Amber Cowell
Programme Administrator
Lancashire Women’s Centres

#EveryWomanCounts    #WellbeingMatters

Website: www.womenscentre.org<http://www.womenscentre.org/>
Follow us on Twitter @WomensCentred  <https://twitter.com/WomensCentred> or on Facebook at Lancashire Women’s Centres<https://www.facebook.com/LancashireWomensCentres>

Accrington Centre:          21-23 Blackburn Road, Accrington, BB5 1HF                        <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.752598,-2.3651487,17z/data=!3m1!4b1!4m5!3m4!1s0x487b98e124d6ab5d:0x7bc5d3d6667714f2!8m2!3d53.752598!4d-2.36296>  Tel. 01254 871771
Blackburn Centre:           25 Wellington Street (St.John’s), Blackburn, BB1 8AF     <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.7526822,-2.4329996,12z/data=!4m8!1m2!2m1!1sBlackburn+lancashire+women's+centres!3m4!1s0x487b9fd28f0b563f:0xf10ab08a862d4f5e!8m2!3d53.752363!4d-2.487995>  Tel. 01254 583032
Blackpool Centre:            162 Church Street, Blackpool, FY1 3PS                                   <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.8186884,-3.0498327,18z/data=!4m8!1m2!2m1!1sBlackpool+lancashire+women's+centres!3m4!1s0x487b4479d15b2e1f:0x4f89954f84f43b26!8m2!3d53.8181!4d-3.047073>  Tel. 01253 290007
Burnley Centre:                4 Nicholas Street, Burnley, BB11 2EU                                     <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.7877591,-2.2450177,17z/data=!3m1!4b1!4m5!3m4!1s0x487b9726a2ce562d:0x4d611847e6a9f5e4!8m2!3d53.787756!4d-2.242829>  Tel. 01282 429672
Preston Centre:                31 Fishergate Hill, Preston, PR1 8DN                                      <https://www.google.co.uk/maps/place/Lancashire+Women's+Centres/@53.7547675,-2.7157778,17z/data=!3m1!4b1!4m5!3m4!1s0x487b727f53e253d3:0xb88145deea32e318!8m2!3d53.7547643!4d-2.7135891>  Tel. 01772 259211

Freephone: 0808 280 3160

This message and any files transmitted with it are confidential and intended solely for the individual(s) addressed.  If you have received this e-mail in error then please note that disclosing, copying or distributing from your system is strictly prohibited.  Any views or opinions presented are solely those of the author and do not necessarily represent those of Lancashire Women's Centres. The organisation accepts no liability for any damage caused by any virus transmitted with this e-mail, so although it has been virus checked before transmission, the recipient should also check for the presence of viruses.  The confidentiality of this email and any subsequent reply cannot be guaranteed

**Comment by Jen-Harris** [comment]
Hey @AmberMCowell, I can't see the images for some reason? 
Did you do it differently last time? Perhaps if you drop the images directly into the comment box rather than replying on email?

**Comment by AmberMCowell** [comment]
![app picture](https://user-images.githubusercontent.com/35597200/35393463-f2f0c386-01dc-11e8-974c-f0ed0e4d2371.jpg)
![app picture 2](https://user-images.githubusercontent.com/35597200/35393464-f3095a7c-01dc-11e8-96ec-56a7bd435079.jpg)
![20171217_165131](https://user-images.githubusercontent.com/35597200/35393466-f473b6a0-01dc-11e8-80ac-6fd9d014df94.jpg)

**Comment by Jen-Harris** [comment]
Great, thank you!
